Preguntas = [
    "Nunca he tenido sexo en un lugar público.",
    "Nunca me he tocado pensando en alguien que conozco.",
    "Nunca he enviado un mensaje subido de tono a la persona equivocada.",
    "Nunca he dicho el nombre equivocado en la cama.",
    "Nunca he tenido un amigo con derecho a roce.",
    "Nunca me he acostado con alguien cuyo nombre no conozco.",
    "Nunca he estado en un sex shop.",
    "Nunca he dudado de mi orientación sexual.",
    "Nunca me he arrepentido de acostarme con alguien.",
    "Nunca me he arrepentido de besar a alguien.",
    "Nunca he hecho sexo tántrico.",
    "Nunca he usado afrodisíacos.",
    "Nunca he probado posturas del kamasutra.",
    "Nunca me he arrepentido de perder mi virginidad con alguien.",
    "Nunca he probado mis propios fluidos.",
    "Nunca he pasado más de un año sin tener sexo.",
    "Nunca me he masturbado delante de alguien.",
    "Nunca he coqueteado con alguien mucho mayor que yo.",
    "Nunca he coqueteado con alguien mucho menor que yo.",
    "Nunca he hecho un trío.",
    "Nunca he tenido una cita a ciegas.",
    "Nunca he tenido sexo en un avión.",
    "Nunca he enviado 'nudes'.",
    "Nunca he fantaseado con un famoso.",
    "Nunca he tenido relaciones con un famoso.",
    "Nunca he tenido relaciones por dinero o por favores.",
    "Nunca he tenido sexo en el mar/piscina.",
    "Nunca he tenido una aventura de una noche.",
    "Nunca he fingido un orgasmo.",
    "Nunca he tenido sexo rápido con alguien.",
    "Nunca he hecho o recibido un baile erótico.",
    "Nunca me he acostado con un compañero de trabajo.",
    "Nunca he vuelto con un ex.",
    "Nunca he sido infiel.",
    "Nunca me he acostado con un ex.",
    "Nunca he fantaseado con un ex.",
    "Nunca he hecho 'bdsm'.",
    "Nunca he mantenido una relación en secreto.",
    "Nunca he usado la comida en el dormitorio.",
    "Nunca me han descubierto mientras tenía relaciones sexuales.",
    "Nunca he tenido un sueño erótico con alguien de esta habitación.",
    "Nunca he tenido un sueño sexual con alguien que la gente de esta habitación conozca.",
    "Nunca he tenido un juguete sexual favorito.",
    "Nunca he jugado a interpretar personajes en la cama.",
    "Nunca me han dado azotes en la cama.",
    "Nunca me he depilado 'por si acaso'.",
    "Nunca he hecho 'sexting'.",
    "Nunca he jugado al 'strip poker'.",
    "Nunca me he masturbado viendo porno.",
    "Nunca me he insinuado a un vecino.",
    "Nunca he leído un libro erótico.",
    "Nunca me he enamorado de quien no debería.",
    "Nunca he tenido sexo borracha.",
    "Nunca he tenido que dejar de tener sexo por estar demasiado borracha.",
    "Nunca he tenido una relación abierta.",
    "Nunca he chupado los dedos de los pies de mi pareja.",
    "Nunca he hecho el paseo de la vergüenza.",
    "Nunca he buscado en Google las posiciones sexuales del Kamasutra.",
    "Nunca he tenido un apodo sexy o le he puesto un apodo sexy a alguien.",
    "Nunca he besado a más de una persona en un día.",
    "Nunca he puesto celosa a mi pareja a propósito.",
    "Nunca he puesto música mientras tengo sexo.",
    "Nunca he tenido que ocultar un chupetón.",
    "Nunca he estado con alguien sin saber su nombre.",
    "Nunca he usado esposas o algo similar.",
    "Nunca he enviado una foto o un vídeo desnuda.",
    "Nunca he grabado un vídeo sexual.",
    "Nunca he tenido un fetiche extraño.",
    "Nunca he fingido dormir para no tener sexo.",
    "Nunca he fingido dolor de cabeza para no tener sexo.",
    "Nunca he usado lubricante.",
    "Nunca he hablado sucio en la cama.",
    "Nunca he hecho cosas indecentes en el cine.",
    "Nunca he mentido sobre alguna experiencia sexual.",
    "Nunca me he masturbado en grupo.",
    "Nunca he visto a alguien teniendo sexo en un coche.",
    "Nunca he tenido sexo en un coche.",
    "Nunca he tenido sexo en la ducha.",
    "Nunca me he excitado con un amigo.",
    "Nunca he entrado en un sex shop.",
    "Nunca he tenido sexo más de tres veces en una noche.",
    "Nunca he tenido sexo con la regla.",
    "Nunca me han pillado teniendo sexo.",
    "Nunca me he quejado del 'tamaño' de alguien.",
    "Nunca he hecho una videollamada picante.",
    "Nunca he salido de casa sin ropa interior.",
    "Nunca he besado a más de tres personas de fiesta.",
    "Nunca me he hecho daño con un juguete sexual.",
    "Nunca he hecho 'squirt'.",
    "Nunca he tenido un sueño erótico con un familiar.",
    "Nunca he tenido sexo borracha.",
    "Nunca he tenido sexo con alguien de otro país.",
    "Nunca he interpretado un juego de 'rol' en la cama.",
    "Nunca he olido mi ropa interior.",
    "Nunca me han visto desnuda de forma accidental.",
    "Nunca he querido imitar una escena porno.",
    "Nunca he visto porno.",
    "Nunca me han dominado en la cama.",
    "Nunca he dominado a alguien en la cama.",
    "Nunca me he sentido atraído por una persona de más de 40 años.",
    "Nunca he hecho una orgía.",
    "Nunca me he acostado con más de una persona la misma noche.",
    "Nunca he tenido sexo en la cama de mis padres.",
    "Nunca me he lesionado mientras tenía relaciones íntimas.",
    "Nunca he mantenido relaciones con alguien 5 años mayor que yo.",
    "Nunca he dicho el nombre equivocado durante una relación.",
    "Nunca he tenido una relación abierta.",
    "Nunca he tomado la pastilla del día después.",
    "Nunca he tenido una enfermedad de transmisión sexual.",
    "Nunca me he hecho daño con un juguete sexual.",
    "Nunca he mandado un audio subido de tono a un familiar por error.", "Yo nunca he dicho el nombre equivocado durante las relaciones sexuales.",
    "Yo nunca he tenido que esconder un chupetón.",
    "Yo nunca he estado con nadie de mi familia.",
    "Yo nunca envié un mensaje caliente a un número equivocado.",
    "Yo nunca he tenido relaciones sexuales con alguien que me doblaba la edad.",
    "Yo nunca pensé que podría tener una ETS.",
    "Yo nunca he usado un objeto común como juguete sexual y lo he devuelto a su sitio.",
    "Yo nunca he hecho un trío.",
    "Yo nunca he tenido una cita a ciegas.",
    "Yo nunca he hecho intercambio de parejas.",
    "Yo nunca he practicado el BDSM.",
    "Yo nunca he hecho sexo tántrico.",
    "Yo nunca he fingido un orgasmo.",
    "Yo nunca he jugado al Strip Poker.",
    "Yo nunca he tenido sexo más de 5 veces en una noche.",
    "Yo nunca quise tener relaciones con una persona del mismo sexo.",
    "Yo nunca me he masturbado al aire libre.",
    "Yo nunca he tenido relaciones sexuales en un coche.",
    "Yo nunca he tenido sexo en la ducha.",
    "Yo nunca he estado en un sex shop.",
    "Yo nunca me he exhibido por webcam.",
    "Yo nunca he sido infiel.",
    "Yo nunca he tenido una relación abierta.",
    "Yo nunca nadé desnudo.",
    "Yo nunca me he liado con el ex de un/a amigo/a.",
    "Yo nunca he vuelto con mi expareja.",
    "Yo nunca me he acostado con mi ex al cabo de un tiempo de terminar.",
    "Yo nunca he tenido relaciones pliamorosas.",
    "Yo nunca he estado con alguien este grupo.",
    "Yo nunca me he disfrazado para cumplir mi fantasía sexual o la de mi pareja.",
    "Yo nunca he probado una de las posturas más difíciles del Kamasutra.",
    "Yo nunca he tenido sexo estando borrachos.",
    "Yo nunca he dominado a alguien durante el sexo.",
    "Yo nunca he hecho la cobra o me la han hecho.",
    "Yo nunca me he imaginado desnudo a alguien de aquí.",
    "Yo nunca me he querido besar con alguien de los aquí presentes.",
    "Yo nunca he tomado afrodisíacos.",
    "Yo nunca me he liado con alguien sin saber su nombre.",
    "Yo nunca he tenido un fetiche extraño.",
    "Yo nunca me he grabado teniendo relaciones.",
    "Yo nunca me he liado con un estudiante de intercambio de mi universidad."
]
