Preguntas = [
    "Nunca he tenido sexo en un lugar público.",
    "Nunca me he tocado pensando en alguien que conozco.",
    "Nunca he enviado un mensaje subido de tono a la persona equivocada.",
    "Nunca he dicho el nombre equivocado en la cama.",
    "Nunca he tenido un amigo con derecho a roce.",
    "Nunca me he acostado con alguien cuyo nombre no conozco.",
    "Nunca he estado en un sex shop.",
    "Nunca he dudado de mi orientación sexual.",
    "Nunca me he arrepentido de acostarme con alguien.",
    "Nunca me he arrepentido de besar a alguien.",
    "Nunca he hecho sexo tántrico.",
    "Nunca he usado afrodisíacos.",
    "Nunca he probado posturas del kamasutra.",
    "Nunca me he arrepentido de perder mi virginidad con alguien.",
    "Nunca he probado mis propios fluidos.",
    "Nunca he pasado más de un año sin tener sexo.",
    "Nunca me he masturbado delante de alguien.",
    "Nunca he coqueteado con alguien mucho mayor que yo.",
    "Nunca he coqueteado con alguien mucho menor que yo.",
    "Nunca he hecho un trío.",
    "Nunca he tenido una cita a ciegas.",
    "Nunca he tenido sexo en un avión.",
    "Nunca he enviado 'nudes'.",
    "Nunca he fantaseado con un famoso.",
    "Nunca he tenido relaciones con un famoso.",
    "Nunca he tenido relaciones por dinero o por favores.",
    "Nunca he tenido sexo en el mar/piscina.",
    "Nunca he tenido una aventura de una noche.",
    "Nunca he fingido un orgasmo.",
    "Nunca he tenido sexo rápido con alguien.",
    "Nunca he hecho o recibido un baile erótico.",
    "Nunca me he acostado con un compañero de trabajo.",
    "Nunca he vuelto con un ex.",
    "Nunca he sido infiel.",
    "Nunca me he acostado con un ex.",
    "Nunca he fantaseado con un ex.",
    "Nunca he hecho 'bdsm'.",
    "Nunca he mantenido una relación en secreto.",
    "Nunca he usado la comida en el dormitorio.",
    "Nunca me han descubierto mientras tenía relaciones sexuales.",
    "Nunca he tenido un sueño erótico con alguien de esta habitación.",
    "Nunca he tenido un sueño sexual con alguien que la gente de esta habitación conozca.",
    "Nunca he tenido un juguete sexual favorito.",
    "Nunca he jugado a interpretar personajes en la cama.",
    "Nunca me han dado azotes en la cama.",
    "Nunca me he depilado 'por si acaso'.",
    "Nunca he hecho 'sexting'.",
    "Nunca he jugado al 'strip poker'.",
    "Nunca me he masturbado viendo porno.",
    "Nunca me he insinuado a un vecino.",
    "Nunca he leído un libro erótico.",
    "Nunca me he enamorado de quien no debería.",
    "Nunca he tenido sexo borracha.",
    "Nunca he tenido que dejar de tener sexo por estar demasiado borracha.",
    "Nunca he tenido una relación abierta.",
    "Nunca he chupado los dedos de los pies de mi pareja.",
    "Nunca he hecho el paseo de la vergüenza.",
    "Nunca he buscado en Google las posiciones sexuales del Kamasutra.",
    "Nunca he tenido un apodo sexy o le he puesto un apodo sexy a alguien.",
    "Nunca he besado a más de una persona en un día.",
    "Nunca he puesto celosa a mi pareja a propósito.",
    "Nunca he puesto música mientras tengo sexo.",
    "Nunca he tenido que ocultar un chupetón.",
    "Nunca he estado con alguien sin saber su nombre.",
    "Nunca he usado esposas o algo similar.",
    "Nunca he enviado una foto o un vídeo desnuda.",
    "Nunca he grabado un vídeo sexual.",
    "Nunca he tenido un fetiche extraño.",
    "Nunca he fingido dormir para no tener sexo.",
    "Nunca he fingido dolor de cabeza para no tener sexo.",
    "Nunca he usado lubricante.",
    "Nunca he hablado sucio en la cama.",
    "Nunca he hecho cosas indecentes en el cine.",
    "Nunca he mentido sobre alguna experiencia sexual.",
    "Nunca me he masturbado en grupo.",
    "Nunca he visto a alguien teniendo sexo en un coche.",
    "Nunca he tenido sexo en un coche.",
    "Nunca he tenido sexo en la ducha.",
    "Nunca me he excitado con un amigo.",
    "Nunca he entrado en un sex shop.",
    "Nunca he tenido sexo más de tres veces en una noche.",
    "Nunca he tenido sexo con la regla.",
    "Nunca me han pillado teniendo sexo.",
    "Nunca me he quejado del 'tamaño' de alguien.",
    "Nunca he hecho una videollamada picante.",
    "Nunca he salido de casa sin ropa interior.",
    "Nunca he besado a más de tres personas de fiesta.",
    "Nunca me he hecho daño con un juguete sexual.",
    "Nunca he hecho 'squirt'.",
    "Nunca he tenido un sueño erótico con un familiar.",
    "Nunca he tenido sexo borracha.",
    "Nunca he tenido sexo con alguien de otro país.",
    "Nunca he interpretado un juego de 'rol' en la cama.",
    "Nunca he olido mi ropa interior.",
    "Nunca me han visto desnuda de forma accidental.",
    "Nunca he querido imitar una escena porno.",
    "Nunca he visto porno.",
    "Nunca me han dominado en la cama.",
    "Nunca he dominado a alguien en la cama.",
    "Nunca me he sentido atraído por una persona de más de 40 años.",
    "Nunca he hecho una orgía.",
    "Nunca me he acostado con más de una persona la misma noche.",
    "Nunca he tenido sexo en la cama de mis padres.",
    "Nunca me he lesionado mientras tenía relaciones íntimas.",
    "Nunca he mantenido relaciones con alguien 5 años mayor que yo.",
    "Nunca he dicho el nombre equivocado durante una relación.",
    "Nunca he tenido una relación abierta.",
    "Nunca he tomado la pastilla del día después.",
    "Nunca he tenido una enfermedad de transmisión sexual.",
    "Nunca me he hecho daño con un juguete sexual.",
    "Nunca he mandado un audio subido de tono a un familiar por error.", "Yo nunca he dicho el nombre equivocado durante las relaciones sexuales.",
    "Yo nunca he tenido que esconder un chupetón.",
    "Yo nunca he estado con nadie de mi familia.",
    "Yo nunca envié un mensaje caliente a un número equivocado.",
    "Yo nunca he tenido relaciones sexuales con alguien que me doblaba la edad.",
    "Yo nunca pensé que podría tener una ETS.",
    "Yo nunca he usado un objeto común como juguete sexual y lo he devuelto a su sitio.",
    "Yo nunca he hecho un trío.",
    "Yo nunca he tenido una cita a ciegas.",
    "Yo nunca he hecho intercambio de parejas.",
    "Yo nunca he practicado el BDSM.",
    "Yo nunca he hecho sexo tántrico.",
    "Yo nunca he fingido un orgasmo.",
    "Yo nunca he jugado al Strip Poker.",
    "Yo nunca he tenido sexo más de 5 veces en una noche.",
    "Yo nunca quise tener relaciones con una persona del mismo sexo.",
    "Yo nunca me he masturbado al aire libre.",
    "Yo nunca he tenido relaciones sexuales en un coche.",
    "Yo nunca he tenido sexo en la ducha.",
    "Yo nunca he estado en un sex shop.",
    "Yo nunca me he exhibido por webcam.",
    "Yo nunca he sido infiel.",
    "Yo nunca he tenido una relación abierta.",
    "Yo nunca nadé desnudo.",
    "Yo nunca me he liado con el ex de un/a amigo/a.",
    "Yo nunca he vuelto con mi expareja.",
    "Yo nunca me he acostado con mi ex al cabo de un tiempo de terminar.",
    "Yo nunca he tenido relaciones pliamorosas.",
    "Yo nunca he estado con alguien este grupo.",
    "Yo nunca me he disfrazado para cumplir mi fantasía sexual o la de mi pareja.",
    "Yo nunca he probado una de las posturas más difíciles del Kamasutra.",
    "Yo nunca he tenido sexo estando borrachos.",
    "Yo nunca he dominado a alguien durante el sexo.",
    "Yo nunca he hecho la cobra o me la han hecho.",
    "Yo nunca me he imaginado desnudo a alguien de aquí.",
    "Yo nunca me he querido besar con alguien de los aquí presentes.",
    "Yo nunca he tomado afrodisíacos.",
    "Yo nunca me he liado con alguien sin saber su nombre.",
    "Yo nunca he tenido un fetiche extraño.",
    "Yo nunca me he grabado teniendo relaciones.",
    "Yo nunca me he liado con un estudiante de intercambio de mi universidad.", 
    "Nunca he pensado en alguien de este grupo como 'algo más'.",
    "Nunca he querido besar a quien está ahora a mi derecha.",
    "Nunca he tenido una fantasía sexual con una persona que está aquí.",
    "Nunca he imaginado a alguien de aquí desnudo/a.",
    "Nunca me he arreglado específicamente para ver a una persona.",
    "Nunca he deseado que una persona que está aquí me bese por todo el cuerpo.",
    "Nunca me he sentido atraída sexualmente por alguien de la sala.",
    "Nunca he anhelado una relación superlarga con alguien que está aquí.",
    "Nunca he fantaseado con quien tengo a la izquierda.",
    "Nunca he soñado con besar a alguien de esta sala.",
    "Nunca he hecho un trío con alguien de la sala.",
    "Nunca he pensado en hacer un trío con alguien que está aquí.",
    "Nunca he 'stalkeado' en Instagram a alguien de esta sala.",
    "Nunca me he tocado pensando en alguien que está aquí.",
    "Nunca me he imaginado teniendo hijos con alguien que tengo cerca ahora mismo.",
    "Nunca he querido que me bese quien tengo ahora enfrente.",
    "Nunca he imaginado que le gusto a alguien de esta habitación.",
    "Nunca sentí nada por alguien de aquí cuando me escribió un mensaje.",
    "Nunca he escrito el nombre de alguien de aquí con un corazoncito al lado.",
    "Nunca me he imaginado casándome con alguien que está presente.",
    "Nunca he querido hacer 'love bombing' a alguien de esta sala.",
    "Nunca he pensado en alguien de esta sala e imaginado que protagonizamos una serie.",
    "Nunca he comparado a nadie de aquí con mi persona ideal.",
    "Nunca he querido hacer un regalo especial a alguien de esta sala.",
    "Nunca he manifestado a alguien de esta habitación.",
    "Nunca he querido salir de fiesta con alguien de esta sala.",
    "Nunca he pensado en declararme a alguien que está aquí mismo.",
    "Nunca he considerado que alguien que está aquí debería estar conmigo.",
    "Nunca he sentido mariposas con quien está mirándome ahora mismo.",
    "Nunca he querido liarme en una discoteca con alguien de aquí.",
    "Nunca he querido chupar la oreja a alguien de aquí.",
    "Nunca he sentido que una persona que está aquí es 'mi persona'.",
    "Nunca he imaginado cosas subidas de tono con quien está dos puestos a mi izquierda.",
    "Nunca he mirado fotos de alguien de aquí con nostalgia.",
    "Nunca me he imaginado en mis vacaciones soñadas con alguien que está en este grupo.",
    "Nunca he pensado en un 'y si' con quien está dos puestos a mi derecha.",
    "Nunca he sentido que no es el momento con alguien de aquí, pero que lo será.",
    "Nunca he pensado en alguien de aquí escuchando canciones románticas.",
    "Nunca se ha colado alguien de aquí en un sueño sexual.",
    "Nunca me he imaginado en un concierto superguay con alguien de aquí.",
    "Nunca he sobrepensado en una persona aquí presente.",
    "Nunca he querido presentar a mis amigos a alguien de aquí como mi pareja.",
    "Nunca he extrañado de manera diferente a alguien de aquí.",
    "Nunca me he tocado pensando en alguien de este grupo.",
    "Nunca he querido saber si le molo a alguien de aquí.",
    "Nunca he pensado de más en quien tengo justo delante.",
    "Nunca he tenido un 'crush'.", 
    "Nunca me he masturbado en un lugar público.",
    "Nunca he hecho un trío entre colegas.",
    "Nunca he pensado en hacer 'ghosting' a mis amigos.",
    "Nunca me he arrepentido de elegir a mis amigos.",
    "Nunca me he besado con la expareja de una amiga.",
    "Nunca me han pillado viendo porno.",
    "Nunca he querido mentir a mi mejor amiga.",
    "Nunca he cotilleado el móvil de una persona que esté aquí.",
    "Nunca he querido saber cómo besa alguien que está aquí.",
    "Nunca he querido robar a alguien que está aquí.",
    "Nunca he deseado acostarme con alguien de este grupo.",
    "Nunca he sentido que no encajaba con alguien de aquí.",
    "Nunca he guardado un secreto a alguien de este grupo.",
    "Nunca me ha caído mal alguien de este grupo.",
    "Nunca he querido ver desnudo a una persona que está aquí.",
    "Nunca he escuchado una canción fantaseando con algún amigo de alguien que está aquí.",
    "Nunca he robado la contraseña de alguna plataforma de 'streaming' de alguien de este grupo.",
    "Nunca he ocultado algo muy fuerte a alguien de aquí.",
    "Nunca he querido tener una relación con un amigo de alguien que está en este grupo.",
    "Nunca he pensado que alguien de aquí es idiota.",
    "Nunca he mentido a alguien de este grupo.",
    "Nunca he organizado planes sin avisar a todo el mundo del grupo.",
    "Nunca he sentido algo muy fuerte por alguien de aquí.",
    "Nunca he criticado a alguien que está aquí.",
    "Nunca he criticado a la pareja de alguien que está aquí.",
    "Nunca he criticado a la familia de alguien que está aquí.",
    "Nunca he cotilleado las 'stories' de alguien de este grupo en modo avión.",
    "Nunca he querido hablar sobre alguien de aquí que me ha traicionado.",
    "Nunca me ha dado pereza ir al cumpleaños de alguien de este grupo.",
    "Nunca he fantaseado con un familiar de alguien aquí presente.",
    "Nunca he escondido algo muy fuerte a alguien de aquí.",
    "Nunca he puesto una excusa para no quedar con alguien que está aquí.",
    "Nunca he mentido sobre el aspecto físico de una persona de aquí.",
    "Nunca he querido huir de alguien que está aquí cuando lo he visto por la calle.",
    "Nunca he fantaseado con alguien de este grupo.",
    "Nunca he pensado en pagar por tener el 'tick' azul de Instagram.",
    "Nunca he cotilleado en modo avión las redes sociales de alguien que me gusta.",
    "Nunca he 'stalkeado' las fotos más antiguas del Instagram de gente de este grupo.",
    "Nunca he pillado el móvil de alguien de este grupo para cotillear.",
    "Nunca he hecho un pantallazo de una 'foto bomba' de alguien que me gusta.",
    "Nunca he mentido sobre algo superfuerte a alguien de este grupo.",
    "Nunca he sentido algo diferente por alguien que está aquí.",
    "Nunca me ha gustado el ex de alguien de este grupo.",
    "Nunca me ha gustado la pareja de alguien de este grupo.",
    "Nunca he inventado un rumor sobre alguien de aquí.",
    "Nunca he pensado en terminar una amistad.",
    "Nunca he tenido ganas de besar a una persona que está aquí ahora mismo.",
    "Nunca he querido acostarme con alguien de aquí y/o su pareja.",
    "Nunca he pensado en cambiar de amigos.",
    "Nunca he dudado de las intenciones de alguien de este grupo.",
    "Yo nunca he tenido sexo en el lugar de trabajo.",
    "Yo nunca he tenido cibersexo.",
    "Yo nunca he llevado una máscara o antifaz en la cama.",
    "Yo nunca pensé que podría tener una ETS.",
    "Yo nunca he probado una de las posturas más difíciles del Kamasutra.",
    "Yo nunca he participado en una orgía.",
    "Yo nunca le he hecho un baile erótico a alguien.",
    "Yo nunca he tenido sexo en la cama de mis padres.",
    "Yo nunca he grabado con el móvil una relación íntima.",
    "Yo nunca me he lesionado mientras tenía relaciones íntimas.",
    "Yo nunca he usado un objeto común como juguete sexual y lo he devuelto a su sitio.",
    "Yo nunca he mantenido relaciones con alguien 5 años mayor que yo.",
    "Yo nunca he mantenido relaciones con alguien 10 años mayor que yo.",
    "Yo nunca me he disfrazado para satisfacer una fantasía.",
    "Yo nunca he estado con nadie de mi familia.",
    "Yo nunca quise tener relaciones con una persona del mismo sexo.",
    "Yo nunca he sido infiel.",
    "Yo nunca me he liado con el ex de un amigo o amiga.",
    "Yo nunca he pasado la noche con alguien de este grupo.",
    "Yo nunca he dicho el nombre equivocado durante una relación.",
    "Yo nunca he hecho un trío.",
    "Yo nunca he tenido una relación sexual con un compañero de trabajo.",
    "Yo nunca le he sido infiel a ninguna de mis parejas.",
    "Yo nunca he tenido relaciones sexuales con alguien que me doblaba la edad.",
    "Yo nunca he tenido una relación abierta.",
    "Yo nunca lo he hecho al aire libre.",
    "Yo nunca he vuelto con mi expareja.",
    "Yo nunca he usado una comida como juguete.",
    "Yo nunca he enviado un desnudo a la persona equivocada.",
    "Yo nunca he intentado ligar con el rollo de un amigo.",
    "Yo nunca he mandado un audio subido de tono a un familiar por error.",
    "Yo nunca he tenido una cita a ciegas.",
    "Yo nunca he estado con alguien de este grupo.",
    "Yo nunca he tenido sexo en el coche.",
    "Yo nunca he usado una aplicación de citas.",
    "Yo nunca me he enamorado de un profe.",
    "Yo nunca he comprado nada en un sex shop.",
    "Yo nunca he tomado una fotografía de mis partes íntimas.",
    "Yo nunca he vomitado mientras tenía relaciones sexuales.",
    "Yo nunca he tomado la pastilla del día después.",
    "Yo nunca he tenido relaciones pliamorosas.",
    "Yo nunca me he sentido atraído por el padre o la madre de un amigo.",
    "Yo nunca he tenido sexo por teléfono.",
    "Yo nunca he pagado una suscripción a una página porno.",
    "Yo nunca he escondido un chupetón a mis padres.",
    "Yo nunca he pensado en otra persona durante el sexo.",
    "Yo nunca he tomado afrodisíacos.",
    "Yo nunca he tenido sexo estando borracho.",
    "Yo nunca he pasado más de seis meses sin tener sexo.",
    "Yo nunca me he liado con alguien sin saber su nombre.",
    "Yo nunca he hecho una cobra (o me la han hecho).",
    "Yo nunca me he acostado con dos personas distintas el mismo día.",
    "Yo nunca he dominado a alguien durante el sexo.",
    "Yo nunca me he acostado con alguien en la primera cita.",
    "Yo nunca he tenido sexo en un avión.",
    "Yo nunca he chupado los dedos de los pies de mi pareja.",
    "Yo nunca he buscado en Google las posiciones sexuales del Kamasutra.",
    "Yo nunca he tenido una fantasía sexual con otra persona cuando estaba en una relación.",
    "Yo nunca he fingido un orgasmo."
]
