Retos = [
    "Enseñar la foto más embarazosa de tu teléfono.",
    "Cambiar tu foto de Whatsapp y poner una que salgas muy mal.",
    "Enseñar las últimas cinco personas a las que enviaste mensajes de texto y lo que decían los mensajes.",
    "Declararte a tu vecino.",
    "Hacerte una foto en una pose ridícula y publicarla en tus redes sociales.",
    "Describe como harías el amor a alguien del grupo.",
    "Cortarte el flequillo.",
    "Cortarte 4 cm de pelo.",
    "Hacerte una foto haciendo la peineta y subirla a Instagram.",
    "Dejar que el resto del grupo envíe un MD a alguien de tu cuenta de Instagram.",
    "Comer un trozo de ajo crudo.",
    "Llamar a un amigo que no esté presente y convencerlo de una historia absurda.",
    "Hacer como que le estás haciendo el amor a alguien por un minuto en el sillón.",
    "Mandar un video tuyo haciendo cosas con una fruta.",
    "Comer media cebolla cruda.",
    "Hacer 100 sentadillas.",
    "Hacer 100 abdominales.",
    "Deja que te hagan cosquillas durante un minuto.",
    "Hacer cosquillas a alguien un minuto.",
    "Toma una cucharada de picante.",
    "Tomarte un vaso de leche del tirón.",
    "Dejar que el grupo mire tus MDs de Instagram.",
    "Mandar un 'selfie' a una persona aleatoria de tu Instagram.",
    "Enseñar tu informe de tiempo en pantalla.",
    "Mantener tres cubitos de hielo en la boca hasta que se derritan.",
    "Decir algo sucio a la persona de tu izquierda.",
    "Hacer una videollamada a un número aleatorio.",
    "Dar un masaje en los pies a la persona de tu derecha.",
    "Pintarle las uñas de los pies a alguien.",
    "Poner 10 líquidos diferentes en un vaso y beberlo.",
    "Gritar la primera palabra que se te ocurra.",
    "Hacer un baile erótico a la persona que elijas.",
    "Repetir todo lo que dice la persona de tu derecha hasta que sea tu turno de nuevo.",
    "Quitarte cuatro prendas de ropa.",
    "Meterte en un cubo de agua helada.",
    "Preguntarle a alguien por la calle si creen que eres atractivo/a.",
    "Abrazar a la primera persona que encuentres.",
    "Gritar a los 4 vientos que te has enamorado.",
    "Correr en ropa interior y descalzo por la calle durante dos minutos.",
    "Llamar a tu pareja y decirle que estás embarazada.",
    "Beberte cuatro vasos de agua seguidos.",
    "Grabar un vídeo de un amigo cantando y compartirlo por 'airdrop'.",
    "Mandar un emoji sugerente a tu jefe.",
    "Echarte jabón de manos en el pelo.",
    "Pintarte las uñas de un color que odies.",
    "Comerte una uña.",
    "Pelar pistachos con la boca.",
    "Comerte una fruta sin pelarla.",
    "Tomar refresco de naranja con un chorro de leche.",
    "Cortarte un mechón de pelo.",
    "Decolorarte las cejas.",
    "Compartir con el resto del grupo un vídeo subido de tono que te guste.",
    "Bailar una canción encima del bar más cercano.",
    "Dar 'me gusta' a las 15 primeras publicaciones de tu Facebook.",
    "Comer una cucharada de mostaza.",
    "Comer una cucharada de ketchup.",
    "Mantener los ojos cerrados hasta que sea tu turno de nuevo.",
    "Intentar meter todos los dedos de un pie en la boca.",
    "Enviar un 'sext' a la última persona de tu agenda telefónica.",
    "Mostrar tu cara de orgasmo.",
    "Entrar en Tinder y mostrar la foto de la primera persona que te llevarías a tu casa.",
    "Escribir una historia erótica de al menos cien palabras y enviarla.",
    "Gemir durante un minuto.",
    "Ronear como un gato durante un minuto.",
    "Grabar un gemido y mandarlo como mensaje de voz.",
    "Comer un plátano de forma seductora.",
    "Vaciar tu cartera/monedero y enseñar a todos lo que hay dentro.",
    "Hacer tu mejor 'gateo sexy'.",
    "Tirarte a una piscina con ropa.",
    "Salir con los pantalones desabrochados.",
    "Salir con los zapatos sin atar/cerrar.",
    "Apagar las luces durante 1 minuto y hacer lo que quieras a los otros jugadores.",
    "Regalar un ramo de flores a una persona de la calle.",
    "Empezar a cantarle una canción a un camarero.",
    "Salir de fiesta sin maquillar.",
    "Leer el primer libro que encuentres con voz sensual.",
    "Lamer la mejilla del jugador que quieras.",
    "Salir al balcón y gritar: ¡fiesta gratis en mi casa!",
    "Subir a Facebook una de tus peores selfies.",
    "Publicar un estado de WhatsApp vergonzoso.",
    "Servir las copas de todo el mundo durante toda la noche.",
    "Hacer tantas flexiones como puedas en un minuto.",
    "Publicar un 'story' vergonzoso.",
    "Ponerte unas pestañas postizas sin mirar al espejo y salir así.",
    "Pintar los labios a un desconocido.",
    "Correr a la pata coja durante dos minutos sin dejar de decir el abecedario.",
    "Fingir ser la persona de tu derecha durante 10 minutos.",
    "Comer un bocadillo sin usar las manos.",
    "Beber una copa sin usar las manos.",
    "Susurrar un secreto a la persona de tu izquierda.",
    "Decir dos cosas sinceras sobre los demás miembros del grupo.",
    "Hacer 'twerking' durante un minuto.",
    "Intentar hacer reír al grupo lo más rápido posible.",
    "Intentar meter todo el puño en la boca.",
    "Dejar que otra persona del grupo te retoque el maquillaje.",
    "Contar a todos una historia embarazosa sobre ti mismo.",
    "Intentar lamerte la nariz.",
    "Pelar un plátano con los dedos de los pies.",
    "Decir todo en un susurro durante los próximos 10 minutos.",
    "Oler la axila de otro jugador.",
    "Morder la oreja a alguien.",
    "Ponerte unos calcetines desaparejados.",
    "Hacerte la sorda durante toda la noche.",
    "Hablar con acento americano durante el resto de la noche.",
    "Hablar con acento mexicano durante toda la noche.",
    "Hacer tu mejor imitación de una 'celebrity'.",
    "Intentar lamerte el codo.",
    "Escribir un mensaje privado a un famoso.",
    "Abrir Tinder y enseñar tus 'matches'.",
    "Proponer una cita a tu último 'match' de Tinder.",
    "Tocar la guitarra aérea durante 2 minutos seguidos.",
    "Mandar un Whatsapp a alguien y borrarlo al segundo.",
    "Publicar el 'selfie' más antiguo de tu teléfono en Instagram Stories.",
    "Contar la historia más triste que conozcas.",
    "Aullar como un lobo durante dos minutos.",
    "Ladrar cada vez que alguien te pregunte algo durante la noche.",
    "Bailar sin música durante dos minutos.",
    "Hacer un striptease a tu pareja.",
    "Hacer 'pole dance' con una barra imaginaria.",
    "Cantar el estribillo de una balada cursi a todo volumen.",
    "Dejar que otra persona te haga cosquillas e intentar no reírte.",
    "Meter en la boca todos los bocadillos que puedas a la vez.",
    "Desplazarte por tu agenda telefónica hasta que alguien te diga que pares. Tienes que llamar o borrar a esa persona.",
    "Ponerte la ropa al revés durante el resto de la noche.",
    "Quitarte la ropa interior.",
    "Salir a la calle sin ropa interior.",
    "Darle de comer a alguien almendras solo utilizando tu boca.",
    "Hablar con una persona fuera del grupo que te atraiga.",
    "Gatear lo más sensualmente posible frente a los demás.",
    "Ponerte la ropa interior de alguien en la cabeza.",
    "Salir a la calle sin zapatos.",
    "Teñirte las cejas de rosa.",
    "Ponerte los calcetines en las manos toda la noche.",
    "Salir una noche con bufanda y gorro.",
    "Invitar a un portero de discoteca a una copa.",
    "Acabarte la bebida (responsablemente).",
    "Intentar llorar delante del grupo.",
    "Hacer reír a un desconocido.",
    "Imitar a un amigo toda la noche.",
    "Estar sin hablar tres horas.",
    "Estar sin hablar toda la noche.",
    "Hacer una imitación de una 'celebrity' para cada persona de la sala.",
    "Decir al grupo dos verdades y una mentira, y ellos tienen que adivinar cuál es la mentira.",
    "Mostrar tu talento secreto.",
    "Contestar con preguntas a las preguntas que te hagan durante 10 minutos.",
    "Tratar de leer un libro mientras te balanceas en una pelota de ejercicio.",
    "Tener una conversación con tu reflejo en el espejo.",
    "Hacerte una máscara de barro o arcilla.",
    "Hacer una carrera de sacos con tus amigos.",
    "Vestirte con un traje ridículo.",
    "Subir una foto sin ropa a las redes sociales.",
    "Enseñar tu última búsqueda en Google.",
    "Hacer 30 flexiones.",
    "Intentar hacer la postura de yoga del árbol durante un minuto.",
    "Bailar el hula hoop durante dos minutos.",
    "Hacer una llamada aleatoria y cantar una canción.",
    "Dar un discurso sobre un tema absurdo.",
    "Hacer un video corto bailando.",
    "Fingir estar enfermo por una hora.",
    "Hacer un video fingiendo que eres un robot.",
    "Mostrar la última foto en tu galería.",
    "Vestirte con la ropa de otra persona.",
    "Recitar un poema en voz alta en un lugar público.",
    "Hacer una rutina de ejercicios de 10 minutos.",
    "Llamar a un amigo y decirle que has ganado la lotería.",
    "Hacer una presentación de ventas de un producto inventado.",
    "Grabar un video cantando tu canción favorita.",
    "Hacer una llamada de broma a un amigo.",
    "Hacer una coreografía para una canción popular.",
    "Compartir una foto de un momento vergonzoso de tu pasado.",
    "Hacer un dibujo con los ojos vendados.",
    "Contar un chiste malo a un grupo de extraños.",
    "Hacer una interpretación dramática de una escena de película.",
    "Cantar en la ducha mientras alguien te graba.",
    "Hacer una serie de selfies en poses ridículas.",
    "Pintar un mural en una pared en blanco.",
    "Intentar hacer malabares con objetos aleatorios.",
    "Contar un secreto divertido.",
    "Hacer una imitación de un animal.",
    "Escribir una carta a tu yo del futuro.",
    "Hacer una batalla de rap improvisada.",
    "Hacer una rutina de comedia.",
    "Dibujar un retrato de alguien en el grupo.",
    "Leer un fragmento de un libro en voz alta.",
    "Hacer una parodia de un video viral.",
    "Hacer una demostración de un truco de magia.",
    "Proponer un reto divertido a otro jugador.",
    "Crear una coreografía para una canción popular y enseñarla.",
    "Hacer un video de 'unboxing' de un objeto aleatorio.",
    "Realizar un experimento científico sencillo.",
    "Mostrar un truco de habilidad.",
    "Hacer un tutorial sobre algo que no sabes hacer.",
    "Compartir una historia inspiradora.",
    "Hacer una recopilación de tus memes favoritos.",
    "Crear una historia ficticia sobre un objeto común.",
    "Hacer una serie de videos con desafíos físicos.",
    "Recitar una lista de cosas que te gustaría hacer antes de morir.",
    "Hacer una reseña de un libro o película.",
    "Crear una lista de cosas que has aprendido este año.",
    "Hacer un dibujo de cómo te imaginas tu vida dentro de 10 años.",
    "Hacer una lista de tus canciones favoritas y compartirla.",
    "Escribir una carta a tu personaje ficticio favorito.",
    "Hacer un video de reacciones a cosas inesperadas.",
    "Recitar una poesía sobre el tema de la amistad.",
    "Hacer un video mostrando tu lugar favorito en tu ciudad.",
    "Realizar una danza improvisada.",
    "Contar un chiste sobre la situación actual.",
    "Hacer una parodia de una serie de televisión.",
    "Crear un video sobre cómo sería un día perfecto para ti.",
    "Hacer un recorrido en video por tu casa.",
    "Compartir una foto de tu lugar favorito para relajarte.",
    "Hacer una presentación sobre un hobby o interés personal.",
    "Grabar un mensaje de agradecimiento a alguien que admires.",
    "Hacer una lista de tus metas para el próximo año.",
    "Contar una historia sobre un sueño extraño.",
    "Hacer una serie de desafíos de destreza.",
    "Compartir una receta de tu plato favorito.",
    "Hacer una demostración de tus habilidades de cocina.",
    "Recitar una cita inspiradora.",
    "Hacer un video de cómo preparas tu bebida favorita.",
    "Hacer una presentación sobre tu lugar de trabajo ideal.",
    "Hacer una rutina de ejercicios en casa.",
    "Compartir una experiencia memorable de viaje.",
    "Hacer un video mostrando cómo haces tu desayuno.",
    "Crear una lista de tus películas favoritas de todos los tiempos.",
    "Hacer una demostración de tus habilidades en un deporte.",
    "Compartir una historia divertida de tu infancia.",
    "Hacer una lista de tus libros favoritos y por qué.",
    "Hacer un video sobre cómo es un día típico en tu vida.",
    "Contar una anécdota graciosa sobre ti mismo.",
    "Crear un video sobre tu lugar favorito para pasar el rato.",
    "Hacer una presentación sobre tus hobbies y pasatiempos.",
    "Recitar una canción en un idioma que no hables.",
    "Hacer una serie de retos de habilidades físicas.",
    "Compartir una experiencia que te haya cambiado la vida.",
    "Hacer una demostración de cómo haces tu actividad favorita.",
    "Crear una lista de tus lugares favoritos para visitar.",
    "Hacer una presentación sobre tus logros personales.",
    "Contar una historia inspiradora de alguien que admires.",
    "Hacer un video mostrando cómo organizas tu espacio de trabajo.",
    "Hacer una lista de tus metas personales y cómo planeas alcanzarlas.",
    "Recitar un poema que te haya marcado.",
    "Hacer un video mostrando cómo preparas una comida especial.",
    "Crear una lista de tus actividades favoritas para el fin de semana.",
    "Hacer una demostración de un truco de habilidad.",
    "Contar una historia sobre un desafío que superaste.",
    "Hacer una presentación sobre tu libro favorito.",
    "Compartir una anécdota divertida de una reunión familiar.",
    "Hacer una serie de videos sobre tus lugares favoritos en tu ciudad.",
    "Contar una historia sobre un logro que te enorgullezca.",
    "Crear una lista de tus canciones favoritas para motivarte.",
    "Hacer una demostración de tus habilidades en un pasatiempo.",
    "Recitar una cita inspiradora sobre la vida.",
    "Hacer un video mostrando cómo preparas una bebida especial.",
    "Hacer una presentación sobre tus sueños y aspiraciones.",
    "Contar una historia sobre una experiencia que te haya sorprendido.",
    "Hacer una lista de tus momentos favoritos del año.",
    "Hacer una demostración de un truco de magia casero.",
    "Compartir una experiencia que te haya hecho reír.",
    "Hacer un video mostrando cómo organizas tu día.",
    "Hacer una presentación sobre un tema que te apasione.",
    "Contar una anécdota graciosa de tus amigos.",
    "Hacer una serie de desafíos de destreza y habilidades.",
    "Recitar un poema que te inspire.",
    "Hacer un video sobre tus lugares favoritos para relajarte.",
    "Compartir una experiencia memorable de tu vida.",
    "Hacer una lista de tus películas favoritas de todos los tiempos.",
    "Crear una presentación sobre tu actividad favorita.",
    "Contar una historia divertida sobre un viaje que hayas hecho.",
    "Hacer una demostración de tus habilidades en un juego de mesa.",
    "Hacer una lista de tus libros favoritos y por qué.",
    "Hacer un video mostrando cómo te preparas para una ocasión especial.",
    "Crear una lista de tus metas personales para el próximo año.",
    "Recitar una cita inspiradora sobre el éxito.",
    "Hacer una presentación sobre tus logros personales.",
    "Compartir una historia sobre un momento que te haya hecho sentir orgulloso."
]
