verdad = [
    "¿Tendrías relaciones con alguien de este grupo?",
    "¿Has tenido relaciones con alguien de este grupo?",
    "¿Quién es la persona más sexy aquí?",
    "¿Alguna vez has pensado en engañar a una pareja tuya?",
    "¿Cuál es tu posición sexual favorita?",
    "¿Quién de las personas de este grupo tiene el cuerpo más bonito?",
    "¿Has tenido relaciones con un desconocido/a?",
    "¿Has tenido sexo en la calle?",
    "¿Alguna vez te han sorprendido teniendo sexo?",
    "¿Alguna vez has dudado de tu orientación sexual?",
    "¿Has quedado con alguien que has conocido en Internet?",
    "¿Con cuántas personas te has acostado?",
    "De este grupo, ¿a quién besarías antes?",
    "¿Alguna vez te has olvidado del nombre de la persona con la que te has acostado?",
    "¿Alguna vez has tenido sexo en la cama de tus padres?",
    "¿Cuál es el mejor lugar para hacerlo?",
    "¿Cómo te describirías en la cama?",
    "¿Cuál es el peor sexo que has tenido en tu vida?",
    "¿Has tenido algún sueño erótico con alguien de aquí?",
    "¿Alguna vez has hecho un trío?",
    "¿Con qué dos personas de aquí harías un trío?",
    "¿Qué es algo que nunca te has atrevido a pedir en la cama?",
    "¿Beso seco, húmedo o mojado?",
    "¿Cuál es tu juguete sexual favorito?",
    "¿Prefieres hacerlo de pie o tumbado?",
    "¿Alguna vez te has acostado con algún familiar de un amigo/a tuyo?",
    "¿Qué harías si fueras del sexo opuesto durante un mes?",
    "¿Has tenido relaciones con alguien de tu mismo sexo?",
    "¿Cuántas fotos tuyas desnudo/a dirías que has mandado?",
    "¿Alguna vez has bebido tanto que te has olvidado de con quién estuviste la noche anterior?",
    "¿Te acostarías con alguien de esta habitación por 1.000€?",
    "¿Alguna vez te han pedido hacer algo en la cama y no te ha gustado?",
    "¿Qué es lo más sucio que has soñado nunca?",
    "¿Pasarías la noche con alguien si te ofrecieran mucho dinero?",
    "¿Consideras que el sexo es imprescindible en una relación?",
    "¿Cuál es la propuesta más indecente que has hecho nunca?",
    "¿Podrías hablarnos de tu fetichismo oculto?",
    "¿Qué opinas honestamente sobre la masturbación?",
    "¿Cuál es tu palabra grosera favorita?",
    "¿Qué es algo que nunca harás en la cama?",
    "¿Alguna vez has tenido que usar un anticonceptivo de emergencia?",
    "¿Has tenido alguna vez sexo tántrico?",
    "¿Cuántas veces lo has hecho en una noche?",
    "¿Serías capaz de matar a alguien?"
]
